### ISSUE TITLE
Ethernet Question.

### ISSUE THREAD

**Issue by salvonos** [Xaver2k/ArduinoENC_Artnet-WS2811#1]
Hi there,
I was interested in trying your code on my a4duino nano. I have opened the .ino file but I can see is a wifi setup. What should I do in order to use it with an ethernet connection end ENC28J60 Ethernet Shield?

**Comment by Xaver2k** [comment]
Hello, where have you seen any wifi setup?? 
This project is made for the ENC28J50 shield wired connection. The main instructions are in the readme file.

**Comment by salvonos** [comment]
Sorry I was opening the wrong project. I have update the code on the arduino Nano attached to the enc28j60 shield. The code uploaded fine however, I cannot connect or ping the arduino using my Mac. Any info?

**Comment by Xaver2k** [comment]
oh sorry, i forgot to reply. did solve the issue?
