### ISSUE TITLE
RGB type

### ISSUE THREAD

**Issue by midnightbegroup** [Xaver2k/ArduinoENC_Artnet-WS2811#2]
I am trying to figure out how to change the LED's from RGB to BRG mode, I have tried changing in the code 'Adafruit_NeoPixel leds1 = Adafruit_NeoPixel(NUMLEDS, DATAPIN1, NEO_BRG + NEO_KHZ800); '

but nothing changes, Any other ideas?

Mike

**Comment by Xaver2k** [comment]
What are you trying to archive?
You need to change the Pixelcolororder in your control software. The color selection in the code is useless, because the software sends the channel signals only.

**Comment by midnightbegroup** [comment]
The software won't let me do it, that's why I'm asking.

Mike

**Comment by Xaver2k** [comment]
I'm sorry, but this code is not receiving or editing any color data. It only forwards channels data. 
Your software determines which color is which channel and sends channel data only to the Arduino. This code then sends these channels data as Pixeldata. The Arduino never gets to know which color you want to output.

Maybe it would be possible to make a channel shifting, but this would take some performance and it's not the arduinos job to make color operations (it's your software's).

Which software are you using?
Any major software i know has adjustable pixelcolor order like Madmapper, jinx!, Madrix ...
